#!/bin/bash

source urls
template="redirect.html"
public_dir="public"
out_dir="dist"

generate_page() {
	local short_url=$1
	local full_url=$2
	sed "s|{url}|$full_url|g" $template > "$out_dir/$short_url.html"
}

rm -rf $out_dir && mkdir $out_dir

cp $public_dir/* $out_dir

for key in "${!urls[@]}"; do
	generate_page "$key" "${urls[$key]}"
done
