#!/bin/bash

export -A urls=(
	["me"]=https://github.com/dragunovartem99
	["git"]=https://github.com/dragunovartem99/myxsu
	["puzzles"]=https://dragunovartem99.github.io/puzzfinder
	["layr"]=https://chromewebstore.google.com/detail/jpdnldokhgdpipodhghfpccajafienfi
)
